version: "3.5"

services:
  application-worker:
    image: $organization$/$name$:latest
    ports:
      - "9090:9090"
    networks:
      - $name$-network

networks:
  $name$-network:
    driver: bridge
    name: $name$-network
